plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: BDHU/minimalist
title: Web Design 1 Fall 2024 Online
description: The website for Web Design 1 Fall 2024 Online

sidebar:
  - name: Home Page (syllabus)
    link: ./
  - name: Student Blogs
    link: ./students
  - name: Week 1 - Introductions
    link: ./week1
  - name: Week 2 - Audits and Analysis
    link: ./week2
  - name: Week 3 - Website Structuring
    link: ./week3
  - name: Week 4 - Homepage Design
    link: ./week4
  - name: Week 5 - Secondary Page Design
    link: ./week5
  - name: Week 6 - Intro to HTML
    link: ./week6
  - name: Week 7 - Midterm Presentations
    link: ./week7
  - name: Week 8 - HTML part 2
    link: ./week8
  - name: Week 9 - Intro to CSS
    link: ./week9
  - name: Week 10 - CSS Part 2
    link: ./week10
  - name: Week 11 - Frameworks
    link: ./week11
  - name: Week 12 - JavaScript
    link: ./week12
  - name: Week 13 - Workshop Day
    link: ./week13
  - name: Week 14 - Final Presentations
    link: ./week14
