plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: BDHU/minimalist
title: Web Design 1 Fall 2024 Online
description: The website for Web Design 1 Fall 2024 Online

sidebar:
  - name: Home Page (syllabus)
    link: ./
  - name: Student Blogs
    link: ./students
  - name: Week 1 - Introductions
    link: ./week1
  - name: Week 2 - Audits and Analysis
    link: ./week2
  - name: Week 3 - Website Structuring
    link: ./week3
  - name: Week 4 - Homepage Design
    link: ./week4
  - name: Week 5 - Secondary Page Design
    link: ./week5
  - name: Week 5 - Secondary Page Design
    link: ./week6
